[package]
name = "biodivine-lib-smt"
version = "0.1.0"
edition = "2024"

[dependencies]
biodivine-lib-param-bn = "0.6.2"
biodivine-lib-bdd = "0.6.2"
z3 = "0.19.2"
num-rational = "0.4.2"
num-traits = "0.2.19"